//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     Version: 1.3001.21.0
//
//     Project:     MSSXpanel
//     Version:     1.0.0.0
//     Sdk:         CH5:2.7.0
//     Strategy:    Modern
//     IndexOnly:   True
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;

namespace MSSXpanel
{
    /// <summary>
    /// Indexed <see cref="EventArgs"/> containing which button or Item was pressed.
    /// </summary>
    public class IndexedEventArgs : EventArgs
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="IndexedEventArgs"/> class.
        /// </summary>
        /// <param name="eventArgs">The <see cref="SmartObjectEventArgs"/> passed back from the panel.</param>
        /// <param name="itemIndex">The position in the Widget List (0 based).</param>
        /// <param name="joinIndex">The position in the Button List (0 based).</param>
        public IndexedEventArgs(SmartObjectEventArgs eventArgs, ushort itemIndex, ushort joinIndex)
        {
            Device = (BasicTriListWithSmartObject)eventArgs.SmartObjectArgs.Device;
            SigArgs = eventArgs;
            ItemIndex = itemIndex;
            JoinIndex = joinIndex;
        }

        /// <summary>
        /// Gets device containing Smart object.
        /// </summary>
        public BasicTriListWithSmartObject Device { get; private set; }

        /// <summary>
        /// Signal arguments of what changed.
        /// </summary>
        public SigEventArgs SigArgs { get; private set; }

        /// <summary>
        /// Return the index within the widget list (0 based).
        /// </summary>
        internal ushort ItemIndex { get; private set; }

        /// <summary>
        /// Return the index within the button list (0 based).
        /// </summary>
        public ushort JoinIndex { get; private set; }
    }

    /// <summary>
    /// Indexed <see cref="EventArgs"/> containing which button was pressed.
    /// </summary>
    public class IndexedButtonEventArgs : IndexedEventArgs
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="IndexedButtonEventArgs"/> class.
        /// </summary>
        /// <param name="eventArgs">The <see cref="SmartObjectEventArgs"/> passed back from the panel.</param>
        /// <param name="buttonIndex">The position of the button pressed in the complex control.</param>
        public IndexedButtonEventArgs(SmartObjectEventArgs eventArgs, ushort buttonIndex) : base(eventArgs, 0, buttonIndex)
        {
        }

        /// <summary>
        /// Return the index within the list e.g. button N in a button list (0 based).
        /// </summary>
        public ushort ButtonIndex
        {
            get { return JoinIndex; }
        } 
    }

    /// <summary>
    /// Indexed <see cref="EventArgs"/> containing which Item was pressed.
    /// </summary>
    public class ItemEventArgs : IndexedEventArgs
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ItemEventArgs"/> class.
        /// </summary>
        /// <param name="eventArgs">The <see cref="SmartObjectEventArgs"/> passed back from the panel.</param>
        /// <param name="widgetItemIndex">The position of the event triggered in the widget list.</param>
        public ItemEventArgs(SmartObjectEventArgs eventArgs, ushort widgetItemIndex) : base(eventArgs, widgetItemIndex, 0)
        {
        }

        /// <summary>
        /// Return the Item index within the Widget List (0 based).
        /// </summary>
        public ushort WidgetItemIndex
        {
            get { return ItemIndex; }
        }
    }

    /// <summary>
    /// Dpad button <see cref="EventArgs"/> containing which button was pressed.
    /// </summary>
    public class DpadEventArgs : IndexedEventArgs
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DpadEventArgs"/> class.
        /// </summary>
        /// <param name="eventArgs">The <see cref="SmartObjectEventArgs"/> passed back from the panel.</param>
        /// <param name="buttonIndex">The position of the button pressed in the complex control.</param>
        public DpadEventArgs(SmartObjectEventArgs eventArgs, DpadButton dpadButton) : base(eventArgs, 0, (ushort)dpadButton)
        {
            DpadButton = dpadButton;
        }

        /// <summary>
        /// </summary>
        public DpadButton DpadButton { get; private set; }
    }

    /// <summary>
    /// Enumerated list of buttons.
    /// </summary>
    public enum DpadButton : ushort
    {
        /// <summary>
        /// Button Up.
        /// </summary>
        Up,
        /// <summary>
        /// Button Down.
        /// </summary>
        Down,
        /// <summary>
        /// Button Left.
        /// </summary>
        Left,
        /// <summary>
        /// Button Right.
        /// </summary>
        Right,
        /// <summary>
        /// Button Center.
        /// </summary>
        Center,
    }

    /// <summary>
    /// Enumerated list of buttons.
    /// </summary>
    public enum KeypadButton : ushort
    {
        /// <summary>
        /// Button 1.
        /// </summary>
        Button_1,
        /// <summary>
        /// Button 2 ABC.
        /// </summary>
        Button_2,
        /// <summary>
        /// Button 3 DEF.
        /// </summary>
        Button_3,
        /// <summary>
        /// Button 4 GHI.
        /// </summary>
        Button_4,
        /// <summary>
        /// Button 5 JKL.
        /// </summary>
        Button_5,
        /// <summary>
        /// Button 6 MNO.
        /// </summary>
        Button_6,
        /// <summary>
        /// Button 7 PQRS.
        /// </summary>
        Button_7,
        /// <summary>
        /// Button 8 TUV.
        /// </summary>
        Button_8,
        /// <summary>
        /// Button 9 WXYZ.
        /// </summary>
        Button_9,
        /// <summary>
        /// Button 0 +.
        /// </summary>
        Button_0,
        /// <summary>
        /// Button Star (*).
        /// </summary>
        Button_Star,
        /// <summary>
        /// Button Hash (#).
        /// </summary>
        Button_Hash,
        /// <summary>
        /// Button Extra (Phone).
        /// </summary>
        Button_Extra,
    }

    /// <summary>
    /// Keypad button <see cref="EventArgs"/> containing which button was pressed.
    /// </summary>
    public class KeypadEventArgs : IndexedEventArgs
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="KeypadEventArgs"/> class.
        /// </summary>
        /// <param name="eventArgs">The <see cref="SmartObjectEventArgs"/> passed back from the panel.</param>
        /// <param name="keypadButton">The button pressed.</param>
        public KeypadEventArgs(SmartObjectEventArgs eventArgs, KeypadButton keypadButton) : base(eventArgs, 0, (ushort)keypadButton)
        {
            KeypadButton = keypadButton;
        }

        /// <summary>
        /// Returns a <see cref="KeypadButton"/> showing the Keypad button that was pressed.
        /// </summary>
        public KeypadButton KeypadButton { get; private set; }
    }
}


